/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ColorPicker: typeof import('./src/components/TopTool/_components/color-picker.vue')['default']
    ContextMenu: typeof import('./src/components/ContextMenu.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElIconBrush: typeof import('@element-plus/icons-vue')['Brush']
    ElIconClose: typeof import('@element-plus/icons-vue')['Close']
    ElIconEdit: typeof import('@element-plus/icons-vue')['Edit']
    ElIconEditPen: typeof import('@element-plus/icons-vue')['EditPen']
    ElIconHide: typeof import('@element-plus/icons-vue')['Hide']
    ElIconLock: typeof import('@element-plus/icons-vue')['Lock']
    ElIconPencile: typeof import('@element-plus/icons-vue')['Pencile']
    ElIconPicture: typeof import('@element-plus/icons-vue')['Picture']
    ElIconPlus: typeof import('@element-plus/icons-vue')['Plus']
    ElIconSearch: typeof import('@element-plus/icons-vue')['Search']
    ElIconSelect: typeof import('@element-plus/icons-vue')['Select']
    ElIconSetting: typeof import('@element-plus/icons-vue')['Setting']
    ElIconUnlock: typeof import('@element-plus/icons-vue')['Unlock']
    ElIconView: typeof import('@element-plus/icons-vue')['View']
    ElIconZoomIn: typeof import('@element-plus/icons-vue')['ZoomIn']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    TopMenu: typeof import('./src/components/TopMenu.vue')['default']
    TopTool: typeof import('./src/components/TopTool/index.vue')['default']
  }
}
