/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CanvasWindow: typeof import('./src/components/FloatWindow/CanvasWindow.vue')['default']
    ColorPicker: typeof import('./src/components/TopTool/_components/ColorPicker.vue')['default']
    ContextMenu: typeof import('./src/components/ContextMenu.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElIconClose: typeof import('@element-plus/icons-vue')['Close']
    ElIconEditPen: typeof import('@element-plus/icons-vue')['EditPen']
    ElIconPicture: typeof import('@element-plus/icons-vue')['Picture']
    ElIconSelect: typeof import('@element-plus/icons-vue')['Select']
    ElIconSetting: typeof import('@element-plus/icons-vue')['Setting']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FloatWindow: typeof import('./src/components/FloatWindow/FloatWindow.vue')['default']
    SuspendedWindow: typeof import('./src/components/SuspendedWindow.vue')['default']
    TopMenu: typeof import('./src/components/TopMenu.vue')['default']
    TopTool: typeof import('./src/components/TopTool/index.vue')['default']
    WorkspaceSetting: typeof import('./src/components/TopTool/_components/WorkspaceSetting.vue')['default']
  }
}
